//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectRunningFox.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApplicationSkinName {
            get {
                return ((string)(this["ApplicationSkinName"]));
            }
            set {
                this["ApplicationSkinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PrintUpdate {
            get {
                return ((bool)(this["PrintUpdate"]));
            }
            set {
                this["PrintUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowUser {
            get {
                return ((bool)(this["ShowUser"]));
            }
            set {
                this["ShowUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Standard Edition")]
        public string UserName {
            get {
                return ((string)(this["UserName"]));
            }
            set {
                this["UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserName1 {
            get {
                return ((string)(this["UserName1"]));
            }
            set {
                this["UserName1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal Opacity {
            get {
                return ((decimal)(this["Opacity"]));
            }
            set {
                this["Opacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 14.25pt, style=Bold")]
        public global::System.Drawing.Font label1Font {
            get {
                return ((global::System.Drawing.Font)(this["label1Font"]));
            }
            set {
                this["label1Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color label1Color {
            get {
                return ((global::System.Drawing.Color)(this["label1Color"]));
            }
            set {
                this["label1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color label1BColor {
            get {
                return ((global::System.Drawing.Color)(this["label1BColor"]));
            }
            set {
                this["label1BColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Time {
            get {
                return ((bool)(this["Time"]));
            }
            set {
                this["Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayUpdates {
            get {
                return ((bool)(this["DisplayUpdates"]));
            }
            set {
                this["DisplayUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color TileBGColor {
            get {
                return ((global::System.Drawing.Color)(this["TileBGColor"]));
            }
            set {
                this["TileBGColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color TileBG2Color {
            get {
                return ((global::System.Drawing.Color)(this["TileBG2Color"]));
            }
            set {
                this["TileBG2Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color TileBGBorderC {
            get {
                return ((global::System.Drawing.Color)(this["TileBGBorderC"]));
            }
            set {
                this["TileBGBorderC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color TileBG2ColorS {
            get {
                return ((global::System.Drawing.Color)(this["TileBG2ColorS"]));
            }
            set {
                this["TileBG2ColorS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color TileBGColorS {
            get {
                return ((global::System.Drawing.Color)(this["TileBGColorS"]));
            }
            set {
                this["TileBGColorS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color TileBGBorderCS {
            get {
                return ((global::System.Drawing.Color)(this["TileBGBorderCS"]));
            }
            set {
                this["TileBGBorderCS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color TileBG2ColorH {
            get {
                return ((global::System.Drawing.Color)(this["TileBG2ColorH"]));
            }
            set {
                this["TileBG2ColorH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color TileBGColorH {
            get {
                return ((global::System.Drawing.Color)(this["TileBGColorH"]));
            }
            set {
                this["TileBGColorH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color TileBGBorderH {
            get {
                return ((global::System.Drawing.Color)(this["TileBGBorderH"]));
            }
            set {
                this["TileBGBorderH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font TileFontNormal {
            get {
                return ((global::System.Drawing.Font)(this["TileFontNormal"]));
            }
            set {
                this["TileFontNormal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color TileFontColor {
            get {
                return ((global::System.Drawing.Color)(this["TileFontColor"]));
            }
            set {
                this["TileFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TextorImage {
            get {
                return ((bool)(this["TextorImage"]));
            }
            set {
                this["TextorImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Call of Duty Series")]
        public string Header1 {
            get {
                return ((string)(this["Header1"]));
            }
            set {
                this["Header1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Battlefield && Assassin\'s Creed")]
        public string Header2 {
            get {
                return ((string)(this["Header2"]));
            }
            set {
                this["Header2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Popular Games")]
        public string Header3 {
            get {
                return ((string)(this["Header3"]));
            }
            set {
                this["Header3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Classic Games")]
        public string Header4 {
            get {
                return ((string)(this["Header4"]));
            }
            set {
                this["Header4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Other Games")]
        public string Header5 {
            get {
                return ((string)(this["Header5"]));
            }
            set {
                this["Header5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Settings and Options")]
        public string Header6 {
            get {
                return ((string)(this["Header6"]));
            }
            set {
                this["Header6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Useful Links")]
        public string Header7 {
            get {
                return ((string)(this["Header7"]));
            }
            set {
                this["Header7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Other Tools")]
        public string Header8 {
            get {
                return ((string)(this["Header8"]));
            }
            set {
                this["Header8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset1 {
            get {
                return ((string)(this["Preset1"]));
            }
            set {
                this["Preset1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset1Code {
            get {
                return ((string)(this["Preset1Code"]));
            }
            set {
                this["Preset1Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset2 {
            get {
                return ((string)(this["Preset2"]));
            }
            set {
                this["Preset2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset2Code {
            get {
                return ((string)(this["Preset2Code"]));
            }
            set {
                this["Preset2Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset3 {
            get {
                return ((string)(this["Preset3"]));
            }
            set {
                this["Preset3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset3Code {
            get {
                return ((string)(this["Preset3Code"]));
            }
            set {
                this["Preset3Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool iPrintLnText {
            get {
                return ((bool)(this["iPrintLnText"]));
            }
            set {
                this["iPrintLnText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset4 {
            get {
                return ((string)(this["Preset4"]));
            }
            set {
                this["Preset4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset4Code {
            get {
                return ((string)(this["Preset4Code"]));
            }
            set {
                this["Preset4Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset5 {
            get {
                return ((string)(this["Preset5"]));
            }
            set {
                this["Preset5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset5Code {
            get {
                return ((string)(this["Preset5Code"]));
            }
            set {
                this["Preset5Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset6 {
            get {
                return ((string)(this["Preset6"]));
            }
            set {
                this["Preset6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset6Code {
            get {
                return ((string)(this["Preset6Code"]));
            }
            set {
                this["Preset6Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset7 {
            get {
                return ((string)(this["Preset7"]));
            }
            set {
                this["Preset7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset7Code {
            get {
                return ((string)(this["Preset7Code"]));
            }
            set {
                this["Preset7Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset8 {
            get {
                return ((string)(this["Preset8"]));
            }
            set {
                this["Preset8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset8Code {
            get {
                return ((string)(this["Preset8Code"]));
            }
            set {
                this["Preset8Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset9 {
            get {
                return ((string)(this["Preset9"]));
            }
            set {
                this["Preset9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset9Code {
            get {
                return ((string)(this["Preset9Code"]));
            }
            set {
                this["Preset9Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset10 {
            get {
                return ((string)(this["Preset10"]));
            }
            set {
                this["Preset10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset10Code {
            get {
                return ((string)(this["Preset10Code"]));
            }
            set {
                this["Preset10Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset11 {
            get {
                return ((string)(this["Preset11"]));
            }
            set {
                this["Preset11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset11Code {
            get {
                return ((string)(this["Preset11Code"]));
            }
            set {
                this["Preset11Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset12 {
            get {
                return ((string)(this["Preset12"]));
            }
            set {
                this["Preset12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset12Code {
            get {
                return ((string)(this["Preset12Code"]));
            }
            set {
                this["Preset12Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset13 {
            get {
                return ((string)(this["Preset13"]));
            }
            set {
                this["Preset13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset13Code {
            get {
                return ((string)(this["Preset13Code"]));
            }
            set {
                this["Preset13Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset14 {
            get {
                return ((string)(this["Preset14"]));
            }
            set {
                this["Preset14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset14Code {
            get {
                return ((string)(this["Preset14Code"]));
            }
            set {
                this["Preset14Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset15 {
            get {
                return ((string)(this["Preset15"]));
            }
            set {
                this["Preset15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset15Code {
            get {
                return ((string)(this["Preset15Code"]));
            }
            set {
                this["Preset15Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset16 {
            get {
                return ((string)(this["Preset16"]));
            }
            set {
                this["Preset16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset16Code {
            get {
                return ((string)(this["Preset16Code"]));
            }
            set {
                this["Preset16Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset17 {
            get {
                return ((string)(this["Preset17"]));
            }
            set {
                this["Preset17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset17Code {
            get {
                return ((string)(this["Preset17Code"]));
            }
            set {
                this["Preset17Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset18 {
            get {
                return ((string)(this["Preset18"]));
            }
            set {
                this["Preset18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset18Code {
            get {
                return ((string)(this["Preset18Code"]));
            }
            set {
                this["Preset18Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font AllLabelsFont {
            get {
                return ((global::System.Drawing.Font)(this["AllLabelsFont"]));
            }
            set {
                this["AllLabelsFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color AllLabelsForeColor {
            get {
                return ((global::System.Drawing.Color)(this["AllLabelsForeColor"]));
            }
            set {
                this["AllLabelsForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font ClientListFont {
            get {
                return ((global::System.Drawing.Font)(this["ClientListFont"]));
            }
            set {
                this["ClientListFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ClientListColor {
            get {
                return ((global::System.Drawing.Color)(this["ClientListColor"]));
            }
            set {
                this["ClientListColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font TextBoxesFont {
            get {
                return ((global::System.Drawing.Font)(this["TextBoxesFont"]));
            }
            set {
                this["TextBoxesFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color TextBoxesForeColor {
            get {
                return ((global::System.Drawing.Color)(this["TextBoxesForeColor"]));
            }
            set {
                this["TextBoxesForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font ButtonsFont {
            get {
                return ((global::System.Drawing.Font)(this["ButtonsFont"]));
            }
            set {
                this["ButtonsFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ButtonsForeColor {
            get {
                return ((global::System.Drawing.Color)(this["ButtonsForeColor"]));
            }
            set {
                this["ButtonsForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font CheckBoxesFont {
            get {
                return ((global::System.Drawing.Font)(this["CheckBoxesFont"]));
            }
            set {
                this["CheckBoxesFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CheckBoxesForeColor {
            get {
                return ((global::System.Drawing.Color)(this["CheckBoxesForeColor"]));
            }
            set {
                this["CheckBoxesForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font TGFont {
            get {
                return ((global::System.Drawing.Font)(this["TGFont"]));
            }
            set {
                this["TGFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color TGForeColor {
            get {
                return ((global::System.Drawing.Color)(this["TGForeColor"]));
            }
            set {
                this["TGForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font CheckButtonFont {
            get {
                return ((global::System.Drawing.Font)(this["CheckButtonFont"]));
            }
            set {
                this["CheckButtonFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CheckButtonForeCOlor {
            get {
                return ((global::System.Drawing.Color)(this["CheckButtonForeCOlor"]));
            }
            set {
                this["CheckButtonForeCOlor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font SpinEditFont {
            get {
                return ((global::System.Drawing.Font)(this["SpinEditFont"]));
            }
            set {
                this["SpinEditFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color SpinEditForeColor {
            get {
                return ((global::System.Drawing.Color)(this["SpinEditForeColor"]));
            }
            set {
                this["SpinEditForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset19 {
            get {
                return ((string)(this["Preset19"]));
            }
            set {
                this["Preset19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset19Code {
            get {
                return ((string)(this["Preset19Code"]));
            }
            set {
                this["Preset19Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset20 {
            get {
                return ((string)(this["Preset20"]));
            }
            set {
                this["Preset20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset20Code {
            get {
                return ((string)(this["Preset20Code"]));
            }
            set {
                this["Preset20Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset21 {
            get {
                return ((string)(this["Preset21"]));
            }
            set {
                this["Preset21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset21Code {
            get {
                return ((string)(this["Preset21Code"]));
            }
            set {
                this["Preset21Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset22 {
            get {
                return ((string)(this["Preset22"]));
            }
            set {
                this["Preset22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset22Code {
            get {
                return ((string)(this["Preset22Code"]));
            }
            set {
                this["Preset22Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset23 {
            get {
                return ((string)(this["Preset23"]));
            }
            set {
                this["Preset23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset23Code {
            get {
                return ((string)(this["Preset23Code"]));
            }
            set {
                this["Preset23Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset24 {
            get {
                return ((string)(this["Preset24"]));
            }
            set {
                this["Preset24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset24Code {
            get {
                return ((string)(this["Preset24Code"]));
            }
            set {
                this["Preset24Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CasePictures {
            get {
                return ((bool)(this["CasePictures"]));
            }
            set {
                this["CasePictures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Tutorial {
            get {
                return ((bool)(this["Tutorial"]));
            }
            set {
                this["Tutorial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CornerChecks {
            get {
                return ((bool)(this["CornerChecks"]));
            }
            set {
                this["CornerChecks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckUpdate {
            get {
                return ((bool)(this["CheckUpdate"]));
            }
            set {
                this["CheckUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public string Hotkey1 {
            get {
                return ((string)(this["Hotkey1"]));
            }
            set {
                this["Hotkey1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset25 {
            get {
                return ((string)(this["Preset25"]));
            }
            set {
                this["Preset25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset25Code {
            get {
                return ((string)(this["Preset25Code"]));
            }
            set {
                this["Preset25Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset26 {
            get {
                return ((string)(this["Preset26"]));
            }
            set {
                this["Preset26"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset26Code {
            get {
                return ((string)(this["Preset26Code"]));
            }
            set {
                this["Preset26Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset27 {
            get {
                return ((string)(this["Preset27"]));
            }
            set {
                this["Preset27"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset27Code {
            get {
                return ((string)(this["Preset27Code"]));
            }
            set {
                this["Preset27Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal FlashInterval {
            get {
                return ((decimal)(this["FlashInterval"]));
            }
            set {
                this["FlashInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal SliderInterval {
            get {
                return ((decimal)(this["SliderInterval"]));
            }
            set {
                this["SliderInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal SkipperInterval {
            get {
                return ((decimal)(this["SkipperInterval"]));
            }
            set {
                this["SkipperInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal RainBowInterval {
            get {
                return ((decimal)(this["RainBowInterval"]));
            }
            set {
                this["RainBowInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string UserTilesCreated {
            get {
                return ((string)(this["UserTilesCreated"]));
            }
            set {
                this["UserTilesCreated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The Tile")]
        public string TileText {
            get {
                return ((string)(this["TileText"]));
            }
            set {
                this["TileText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TilePath {
            get {
                return ((string)(this["TilePath"]));
            }
            set {
                this["TilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 8.25pt")]
        public global::System.Drawing.Font TileFont {
            get {
                return ((global::System.Drawing.Font)(this["TileFont"]));
            }
            set {
                this["TileFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color TileFC {
            get {
                return ((global::System.Drawing.Color)(this["TileFC"]));
            }
            set {
                this["TileFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color TileBC {
            get {
                return ((global::System.Drawing.Color)(this["TileBC"]));
            }
            set {
                this["TileBC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color TileBG {
            get {
                return ((global::System.Drawing.Color)(this["TileBG"]));
            }
            set {
                this["TileBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AvatarIndex {
            get {
                return ((string)(this["AvatarIndex"]));
            }
            set {
                this["AvatarIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MemberStatus {
            get {
                return ((string)(this["MemberStatus"]));
            }
            set {
                this["MemberStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PreferredAPI {
            get {
                return ((bool)(this["PreferredAPI"]));
            }
            set {
                this["PreferredAPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PreferredAPI1 {
            get {
                return ((bool)(this["PreferredAPI1"]));
            }
            set {
                this["PreferredAPI1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BETACountDown {
            get {
                return ((string)(this["BETACountDown"]));
            }
            set {
                this["BETACountDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HotKey2 {
            get {
                return ((string)(this["HotKey2"]));
            }
            set {
                this["HotKey2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TilePath1 {
            get {
                return ((string)(this["TilePath1"]));
            }
            set {
                this["TilePath1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TileText1 {
            get {
                return ((string)(this["TileText1"]));
            }
            set {
                this["TileText1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TilePath2 {
            get {
                return ((string)(this["TilePath2"]));
            }
            set {
                this["TilePath2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TileText2 {
            get {
                return ((string)(this["TileText2"]));
            }
            set {
                this["TileText2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Tips {
            get {
                return ((bool)(this["Tips"]));
            }
            set {
                this["Tips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RPCinitialize {
            get {
                return ((bool)(this["RPCinitialize"]));
            }
            set {
                this["RPCinitialize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GenerateUnmandatory {
            get {
                return ((bool)(this["GenerateUnmandatory"]));
            }
            set {
                this["GenerateUnmandatory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImageUrl {
            get {
                return ((string)(this["ImageUrl"]));
            }
            set {
                this["ImageUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color chatBackColor {
            get {
                return ((global::System.Drawing.Color)(this["chatBackColor"]));
            }
            set {
                this["chatBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color chatForeColor {
            get {
                return ((global::System.Drawing.Color)(this["chatForeColor"]));
            }
            set {
                this["chatForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font chatFont {
            get {
                return ((global::System.Drawing.Font)(this["chatFont"]));
            }
            set {
                this["chatFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color usersOnlineBackColor {
            get {
                return ((global::System.Drawing.Color)(this["usersOnlineBackColor"]));
            }
            set {
                this["usersOnlineBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color usersOnlineForeColor {
            get {
                return ((global::System.Drawing.Color)(this["usersOnlineForeColor"]));
            }
            set {
                this["usersOnlineForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font usersOnlineFont {
            get {
                return ((global::System.Drawing.Font)(this["usersOnlineFont"]));
            }
            set {
                this["usersOnlineFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color messageBackColor {
            get {
                return ((global::System.Drawing.Color)(this["messageBackColor"]));
            }
            set {
                this["messageBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color messageForeColor {
            get {
                return ((global::System.Drawing.Color)(this["messageForeColor"]));
            }
            set {
                this["messageForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font messageFont {
            get {
                return ((global::System.Drawing.Font)(this["messageFont"]));
            }
            set {
                this["messageFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool remainAnonymous {
            get {
                return ((bool)(this["remainAnonymous"]));
            }
            set {
                this["remainAnonymous"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoClearChat {
            get {
                return ((bool)(this["autoClearChat"]));
            }
            set {
                this["autoClearChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset28 {
            get {
                return ((string)(this["Preset28"]));
            }
            set {
                this["Preset28"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset28Code {
            get {
                return ((string)(this["Preset28Code"]));
            }
            set {
                this["Preset28Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset29 {
            get {
                return ((string)(this["Preset29"]));
            }
            set {
                this["Preset29"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset29Code {
            get {
                return ((string)(this["Preset29Code"]));
            }
            set {
                this["Preset29Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset30 {
            get {
                return ((string)(this["Preset30"]));
            }
            set {
                this["Preset30"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string Preset30Code {
            get {
                return ((string)(this["Preset30Code"]));
            }
            set {
                this["Preset30Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SeasonalTheme {
            get {
                return ((bool)(this["SeasonalTheme"]));
            }
            set {
                this["SeasonalTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableURLAvatar {
            get {
                return ((bool)(this["EnableURLAvatar"]));
            }
            set {
                this["EnableURLAvatar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CCAPIMessage {
            get {
                return ((bool)(this["CCAPIMessage"]));
            }
            set {
                this["CCAPIMessage"] = value;
            }
        }
    }
}
